FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

COPY requirements-core.txt requirements-optional.txt requirements-worker.txt requirements-dev.txt ./

RUN pip install --upgrade pip \
    && pip install -r requirements-dev.txt

COPY app ./app
COPY migrations ./migrations
COPY scripts ./scripts
COPY tests ./tests
COPY pytest.ini ./

CMD ["python", "-m", "pytest"]
