import * as React from 'react';
import * as LabelPrimitive from '@radix-ui/react-label';
import { cn } from '@/lib/utils';
const FormItem = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (<div ref={ref} className={cn('space-y-2', className)} {...props} />));
FormItem.displayName = 'FormItem';
const FormLabel = React.forwardRef<React.ElementRef<typeof LabelPrimitive.Root>, React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>>(({ className, ...props }, ref) => (<LabelPrimitive.Root ref={ref} className={cn('text-sm font-medium', className)} {...props} />));
FormLabel.displayName = 'FormLabel';
const FormControl = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ ...props }, ref) => (<div ref={ref} {...props} />));
FormControl.displayName = 'FormControl';
const FormMessage = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(({ className, children, ...props }, ref) => (<p ref={ref} className={cn('text-sm text-destructive', className)} {...props}>{children}</p>));
FormMessage.displayName = 'FormMessage';
export { FormItem, FormLabel, FormControl, FormMessage };
